# portfolio_config.yaml
student_file: content/brendan_hunt.yaml

projects:
  - content/projects/medical_classifier.yaml
  - content/projects/riot_pipeline.yaml
  - content/projects/aws_nyc311.yaml 

theme: msu-dark
site_title: "Brendan Hunt | Data Science Portfolio"